// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://blgocjhftikjxqndnnzy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJsZ29jamhmdGlranhxbmRubnp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI5OTM3NzMsImV4cCI6MjA4ODU2OTc3M30.vsQWL1nLqkMLG-uLLa_9oW3hzlrv2m2nV7XraGxnjwU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});